Repository Azure/Azure-Orbital-Analytics-Samples, pull requests merged in 2022-06, with the labels that each got.

#31 Adds CI/CD test pipeline
  .github/workflows/run-setup-script.yml
  .gitignore
  deploy/cleanup.sh
  deploy/configure.sh
  deploy/infra/create_cpu_batch_account_pool.bicep
  deploy/infra/groups/orchestration.bicep
  deploy/infra/main.bicep
  deploy/install.sh
  deploy/package.sh
  deploy/setup.sh
  test/batch_account.py
  test/check-pipeline-status.sh
  test/create-pipeline-install-commands.py
  test/custom-vision-model-parameters.json
  test/custom-vision-model-v2-parameters.json
  test/deploy-prepare-and-test-pipeline.sh
  test/use-pre-provisioned-batch-account.sh
Labels: enhancement

#37 Data load to PostgreSQL database
  .github/workflows/run-setup-script.yml
  deploy/CVModelSQLScript.sql
  deploy/README.md
  deploy/environment.yml
  deploy/infra/groups/data.bicep
  deploy/infra/main.bicep
  deploy/infra/modules/aci.bicep
  deploy/infra/modules/aci.delete.bicep
  deploy/infra/modules/postgres.single.svc.bicep
  deploy/install.sh
  deploy/package.py
  deploy/package.sh
  src/workflow/custom-vision-model-v2/notebook/Insert CV Object Detection Data Into DB Notebook Job.json
  src/workflow/custom-vision-model-v2/pipeline/E2E Custom Vision Model Flow.json
Labels: enhancement

#46 Added notebook creation to pipeline dependencies
  test/create-pipeline-install-commands.py
Labels: enhancement

#47 Fix the condition check for AAD_GROUP_PRINCIPAL_ID
  .github/workflows/run-setup-script.yml
Labels: bug

#50 Fixing cleanup.sh
  deploy/cleanup.sh
Labels: bug

#52 Adds a flag DEPLOY_PGSQL to manage postgresql database server deployment
  deploy/infra/groups/data.bicep
  deploy/infra/main.bicep
  deploy/install.sh
  deploy/package.py
  deploy/package.sh
  deploy/setup.sh
Labels: enhancement

#58 Creates ADO test pipeline
  azure-pipelines/PR-pipeline.yml
Labels: CI/CD

#61 Copy noop replaced with data flow
  src/workflow/custom-vision-model-v2/dataset/run_container.json
  src/workflow/custom-vision-model-v2/dataset/run_fileshare.json
  src/workflow/custom-vision-model-v2/pipeline/Custom Vision Object Detection v2.json
Labels: enhancement

#64 Update readme.md with optional parameters
  deploy/README.md
Labels: documentation

#65 Added DisableDockerDetector to pipeline definition
  azure-pipelines/PR-pipeline.yml
Labels: bug, CI/CD

#49 Make entrypoint for multiple AI platform
  deploy/README.md
  deploy/cleanup.sh
  deploy/configure.sh
  deploy/infra/groups/orchestration.bicep
  deploy/infra/main.bicep
  deploy/install.sh
  deploy/package.sh
  deploy/setup.sh
Labels: enhancement

#68 Use postgresql with pipelines
  azure-pipelines/PR-pipeline.yml
Labels: CI/CD

#70 Use variable instead of parameter in ado pipeline
  azure-pipelines/PR-pipeline.yml
Labels: CI/CD
